# springboot
server:
  port: 8080
  tomcat:
    max-http-form-post-size: -1

logging:
  level:
    org:
      springframework: INFO

# SPRING
spring:
  datasource:
    # 개선 커넥션 풀 db사용
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://192.168.10.7:5432/postgres
      username: postgres
      password: postgres
  # SPRING JPA Config
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      use-new-id-generator-mappings: true
    show-sql: true
    open-in-view: false